# Generated by Django 4.1.6 on 2023-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Vaga",
                "verbose_name_plural": "Vagas",
            },
        ),
    ]
